# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92f2fe2ba2da873fabdeff4b0b03a6070ff6296aa2a8eb6464b60839cd4a1f4b19fc9c78124f43a90841ea725341bd255e3fe2a47b7cfd6a38b46e53ba5e10e5

test:
  secret_key_base: 2dbf51a9b1afb97817dd90ab0061281150df95ff8fed1ab36662e63c19e3a9dc84f4dc6c9ad9f22bae53eeaa18efe178d001d91be2324e82241a385f9f11b041

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
